### ISSUE TITLE
Error "field 'PAR' has incomplete type"

### ISSUE THREAD

**Issue by KevinIMA** [br-automation-com/AS-USB#3]
I have pulled the USBDevice program into mines and it seems to work fine when just doing a build and transfer but when I started a full rebuild, I get the error "field 'PAR' has incomplete type". Removing the program and replacing with a new one seems to fix this issue until I do another full rebuild. The error points to the generated file usbtypesTYP.h [Header File] line 43.

**Comment by stephan1827** [comment]
I tried the latest release and source code and they seem to work fine.

- What Automation Studio are you using?
- What compiler version are you using?
- Can you post the content of usbtypesTYP.h file

**Comment by KevinIMA** [comment]
Automation Runtime B4.63
GCC Build V6.3.0

I have attached pictures and also copied the contents of usbtypesTyp.h into a text file.

The always repeated 6 times in the output. All pointing to line 43 of usbtypesTYP.h “struct usbPAR PAR;”

To reiterate, a fresh install of the USBdevice program into my project works fine as long as I build and transfer but when I initiate a full rebuild, the errors will appear and will not go away even if I try a normal build and transfer.

**Comment by stephan1827** [comment]
There is a comment in the header file that describes the issue

_/* Data type usbPAR not declared. Data types with array elements whose starting indexes are not equal to zero cannot be used in ANSI C programs / libraries.*/_

The variable 'is_connected' starts at index 1. I did this because it is more natural to start counting from 1 instead of 0. Unfortunately C does not like arrays that don't start at 0. As a quick workaround you can just change the array to start
at 0.

**Comment by KevinIMA** [comment]
I had seen this comment but was not too familiar with this subject to understand.

I have changed the array to start at 0 and changed the value of USB_MAX_CNT to 4 and everything seems to compile correctly.

With this change, will the first USB I insert still be called USB_DEVICE1 or will this change to USB_DEVICE0?

**Comment by stephan1827** [comment]
Yes, the first will still be USB_DEVICE1
